---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	perceive(perceive)
	compile(compile)
	human_review(human_review)
	deploy(deploy<hr/><small><em>__interrupt = before</em></small>)
	self_heal(self_heal)
	__end__([<p>__end__</p>]):::last
	__start__ --> perceive;
	compile --> human_review;
	deploy -.-> __end__;
	deploy -.-> self_heal;
	human_review -.-> __end__;
	human_review -.-> deploy;
	perceive --> compile;
	self_heal --> deploy;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
